-- ===================================================================
-- 02 - INSPEÇÃO COMPLETA DE ESTOQUE POR CONTROLE
-- ===================================================================
-- Objetivo: Análise detalhada de todos os aspectos do estoque por controle
-- Uso: Execute após o diagnóstico rápido para investigação profunda
-- ===================================================================

-- Configuração (ajuste conforme necessário)
DECLARE @CODPROD INT = 15664;          -- Código do produto com problema
DECLARE @CODEMP SMALLINT = 1;           -- Empresa
DECLARE @CODLOCAL INT = 111003;          -- Local do estoque
DECLARE @CONTROLE_PROBLEMA VARCHAR(100) = '9/16" X 10'; -- Controle que está causando erro

PRINT '=== INSPEÇÃO COMPLETA DE ESTOQUE POR CONTROLE ===';
PRINT 'Produto: ' + CAST(@CODPROD AS VARCHAR(10));
PRINT 'Empresa: ' + CAST(@CODEMP AS VARCHAR(5));
PRINT 'Local: ' + CAST(@CODLOCAL AS VARCHAR(10));
PRINT 'Controle problemático: "' + @CONTROLE_PROBLEMA + '"';
PRINT 'Data/Hora: ' + CONVERT(VARCHAR, GETDATE(), 120);
PRINT '';

-- 1. ANÁLISE COMPARATIVA DE CONTROLES
PRINT '=== 1. ANÁLISE COMPARATIVA DE TODOS OS CONTROLES ===';
SELECT 
    E.CONTROLE,
    E.ESTOQUE AS ESTOQUE_FISICO,
    E.RESERVADO AS ESTOQUE_RESERVADO,
    ISNULL(E.WMSBLOQUEADO, 0) AS BLOQUEADO_WMS,
    (E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) AS DISPONIVEL_CALCULADO,
    E.STATUSLOTE,
    E.ATIVO,
    CASE 
        WHEN E.ATIVO = 'N' THEN '❌ INATIVO'
        WHEN E.ESTOQUE <= 0 THEN '❌ ZERADO'
        WHEN (E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) <= 0 THEN '❌ INDISPONÍVEL'
        ELSE '✅ DISPONÍVEL'
    END AS STATUS,
    L.DESCLOCAL,
    CASE 
        WHEN LEN(E.CONTROLE) = 0 THEN '🔴 VAZIO'
        WHEN CHARINDEX('"', E.CONTROLE) > 0 THEN '🟡 COM ASPAS'
        WHEN CHARINDEX(' ', E.CONTROLE) > 0 THEN '🟡 COM ESPAÇO'
        ELSE '🟢 NORMAL'
    END AS TIPO_CONTROLE,
    CASE 
        WHEN E.CONTROLE = @CONTROLE_PROBLEMA THEN '⚠️ PROBLEMÁTICO'
        ELSE ''
    END AS MARCA
FROM TGFEST E WITH (NOLOCK)
LEFT JOIN TGFLOC L WITH (NOLOCK) ON E.CODLOCAL = L.CODLOCAL
WHERE E.CODPROD = @CODPROD 
  AND E.CODEMP = @CODEMP 
  AND E.CODLOCAL = @CODLOCAL 
  AND E.CODPARC = 0
ORDER BY 
    CASE WHEN E.CONTROLE = @CONTROLE_PROBLEMA THEN 0 ELSE 1 END,
    E.CONTROLE;
PRINT '';

-- 2. VERIFICAÇÃO DE CARACTERES ESPECIAIS NO CONTROLE PROBLEMÁTICO
PRINT '=== 2. ANÁLISE DO CONTROLE PROBLEMÁTICO ===';
DECLARE @CONTROLES_SIMILARES TABLE (
    CONTROLE VARCHAR(100),
    ESTOQUE FLOAT,
    DISPONIVEL FLOAT,
    STATUS VARCHAR(10)
);

-- Busca controles similares (com variações de caracteres)
INSERT INTO @CONTROLES_SIMILARES
SELECT 
    E.CONTROLE,
    E.ESTOQUE,
    (E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) AS DISPONIVEL,
    CASE 
        WHEN (E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) > 0 THEN 'DISPONÍVEL'
        ELSE 'INDISPONÍVEL'
    END AS STATUS
FROM TGFEST E WITH (NOLOCK)
WHERE E.CODPROD = @CODPROD 
  AND E.CODEMP = @CODEMP 
  AND E.CODLOCAL = @CODLOCAL 
  AND E.CODPARC = 0
  AND (
        E.CONTROLE LIKE REPLACE(@CONTROLE_PROBLEMA, '"', '%')  -- Comparação sem aspas
        OR REPLACE(@CONTROLE_PROBLEMA, '"', '') LIKE '%' + E.CONTROLE + '%'  -- Busca contém
        OR REPLACE(@CONTROLE_PROBLEMA, '"', '') LIKE '%' + E.CONTROLE + '%'  -- Busca contida
        OR REPLACE(REPLACE(E.CONTROLE, '"', ''), ' ', '') = REPLACE(REPLACE(@CONTROLE_PROBLEMA, '"', ''), ' ', '')  -- Comparação sem espaços
    );

PRINT 'Controle original: "' + @CONTROLE_PROBLEMA + '"';
PRINT 'Análise de caracteres:';
PRINT '  - Comprimento: ' + CAST(LEN(@CONTROLE_PROBLEMA) AS VARCHAR(10));
PRINT '  - Contém aspas: ' + CASE WHEN CHARINDEX('"', @CONTROLE_PROBLEMA) > 0 THEN 'SIM' ELSE 'NÃO' END;
PRINT '  - Contém espaços: ' + CASE WHEN CHARINDEX(' ', @CONTROLE_PROBLEMA) > 0 THEN 'SIM' ELSE 'NÃO' END;
PRINT '';
PRINT 'Controles similares encontrados:';
SELECT * FROM @CONTROLES_SIMILARES;
PRINT '';

-- 3. HISTÓRICO DE MOVIMENTAÇÕES DO ESTOQUE
PRINT '=== 3. HISTÓRICO RECENTE DE MOVIMENTAÇÕES ===';
SELECT TOP 20
    H.DTALTER AS DATA_MOVIMENTACAO,
    H.CODLOCAL,
    H.CONTROLE,
    H.HISTORICO AS TIPO_MOVIMENTACAO,
    H.ESTOQUE_ANT AS ESTOQUE_ANTES,
    H.ESTOQUE_ATU AS ESTOQUE_DEPOIS,
    H.QTDMOV AS QUANTIDADE_MOVIMENTADA,
    H.DOC AS DOCUMENTO_RELACIONADO,
    CASE 
        WHEN H.HISTORICO LIKE '%ENTRADA%' THEN '📥 ENTRADA'
        WHEN H.HISTORICO LIKE '%SAÍDA%' THEN '📤 SAÍDA'
        WHEN H.HISTORICO LIKE '%AJUSTE%' THEN '🔧 AJUSTE'
        WHEN H.HISTORICO LIKE '%BLOQUEIO%' THEN '🔒 BLOQUEIO'
        WHEN H.HISTORICO LIKE '%RESERVA%' THEN '⏸ RESERVA'
        ELSE '📋 ' + H.HISTORICO
    END AS CATEGORIA
FROM TGFHES H WITH (NOLOCK)
WHERE H.CODPROD = @CODPROD 
  AND H.CODEMP = @CODEMP 
  AND H.CODLOCAL = @CODLOCAL 
  AND H.DTALTER >= DATEADD(DAY, -30, GETDATE())  -- Últimos 30 dias
ORDER BY H.DTALTER DESC;
PRINT '';

-- 4. VERIFICAÇÃO DE BLOQUEIOS E RESERVAS ESPECÍFICAS
PRINT '=== 4. BLOQUEIOS E RESERVAS ESPECÍFICAS ===';

-- Bloqueios por controle
SELECT 
    'BLOQUEIOS POR CONTROLE' AS TIPO_ANALISE,
    E.CONTROLE,
    COUNT(*) AS QUANTIDADE_BLOQUEIOS,
    SUM(E.WMSBLOQUEADO) AS TOTAL_BLOQUEADO
FROM TGFBLO B WITH (NOLOCK)
INNER JOIN TGFEST E WITH (NOLOCK) ON B.CODPROD = E.CODPROD 
    AND B.CODEMP = E.CODEMP 
    AND B.CODLOCAL = E.CODLOCAL 
    AND B.CONTROLE = E.CONTROLE
WHERE B.CODPROD = @CODPROD 
  AND B.CODEMP = @CODEMP 
  AND B.CODLOCAL = @CODLOCAL
  AND B.DTBLOQUE <= GETDATE()
  AND B.DTBLOQFIN > GETDATE()
GROUP BY E.CONTROLE
HAVING COUNT(*) > 0;

-- Reservas detalhadas
SELECT 
    'RESERVAS DETALHADAS' AS TIPO_ANALISE,
    I.NUNOTA,
    I.SEQUENCIA,
    I.CONTROLE AS CONTROLE_RESERVA,
    I.QTDNEG,
    I.RESERVA,
    I.QTDENTREGUE,
    C.DESCRCAB AS TIPO_OPERACAO,
    I.DTALTER AS DATA_RESERVA,
    CASE 
        WHEN C.DTENTRADA IS NOT NULL THEN '✅ NOTA FISCAL'
        ELSE '📝 PEDIDO/ORÇAMENTO'
    END AS TIPO_DOCUMENTO
FROM TGFITE I WITH (NOLOCK)
LEFT JOIN TGFCAB C WITH (NOLOCK) ON I.NUNOTA = C.NUNOTA
LEFT JOIN TGFTOP T WITH (NOLOCK) ON C.CODTIPOPER = T.CODTIPOPER AND C.DHTIPOPER = T.DHALTER
WHERE I.CODPROD = @CODPROD 
  AND I.RESERVA > 0
  AND I.QTDNEG > I.QTDENTREGUE
ORDER BY I.DTALTER DESC;
PRINT '';

-- 5. VERIFICAÇÃO DE ESTOQUE EM OUTROS LOCAIS
PRINT '=== 5. ESTOQUE EM OUTROS LOCAIS ===';
SELECT 
    L.CODLOCAL,
    L.DESCLOCAL,
    COUNT(DISTINCT E.CONTROLE) AS QTD_CONTROLES,
    SUM(E.ESTOQUE) AS ESTOQUE_TOTAL,
    SUM(E.RESERVADO) AS RESERVADO_TOTAL,
    SUM(E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) AS DISPONIVEL_TOTAL,
    MIN(E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) AS MENOR_DISPONIVEL,
    MAX(E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) AS MAIOR_DISPONIVEL
FROM TGFEST E WITH (NOLOCK)
INNER JOIN TGFLOC L WITH (NOLOCK) ON E.CODLOCAL = L.CODLOCAL
WHERE E.CODPROD = @CODPROD 
  AND E.CODEMP = @CODEMP 
  AND E.CODPARC = 0
  AND E.ATIVO = 'S'
GROUP BY L.CODLOCAL, L.DESCLOCAL
ORDER BY SUM(E.ESTOQUE - E.RESERVADO - ISNULL(E.WMSBLOQUEADO, 0)) DESC;
PRINT '';

-- 6. ANÁLISE DE POSSÍVEIS CORREÇÕES
PRINT '=== 6. RECOMENDAÇÕES DE CORREÇÃO ===';
DECLARE @TEM_CONTROLE_VALIDO BIT = 0;
DECLARE @TEM_SIMILAR_DISPONIVEL BIT = 0;
DECLARE @TEM_OUTRO_LOCAL_DISPONIVEL BIT = 0;

-- Verificações
IF EXISTS(
    SELECT 1 FROM @CONTROLES_SIMILARES 
    WHERE CONTROLE = @CONTROLE_PROBLEMA 
      AND STATUS = 'DISPONÍVEL'
      AND DISPONIVEL > 0
)
    SET @TEM_CONTROLE_VALIDO = 1;

IF EXISTS(
    SELECT 1 FROM @CONTROLES_SIMILARES 
    WHERE STATUS = 'DISPONÍVEL' 
      AND DISPONIVEL > 0
)
    SET @TEM_SIMILAR_DISPONIVEL = 1;

SELECT 
    'OPÇÕES DE CORREÇÃO' AS SITUACAO,
    RECOMENDACAO,
    COMANDO_SQL,
    PRIORIDADE
FROM (
    -- Opção 1: O controle existe e tem estoque
    SELECT 
        1 AS PRIORIDADE,
        'CONTROLE VÁLIDO ENCONTRADO' AS SITUACAO,
        'O controle "' + @CONTROLE_PROBLEMA + '" existe e tem estoque disponível. Verifique se há outro problema na nota.' AS RECOMENDACAO,
        '-- Verificar o item na nota: SELECT * FROM TGFITE WHERE NUNOTA = [NUMERO_NOTA] AND SEQUENCIA = [SEQUENCIA]' AS COMANDO_SQL
    WHERE @TEM_CONTROLE_VALIDO = 1
    
    UNION ALL
    
    -- Opção 2: Controle similar disponível
    SELECT 
        2 AS PRIORIDADE,
        'CONTROLE SIMILAR DISPONÍVEL' AS SITUACAO,
        'Use o controle "' + (SELECT TOP 1 CONTROLE FROM @CONTROLES_SIMILARES WHERE STATUS = 'DISPONÍVEL' ORDER BY DISPONIVEL DESC) + '" no lugar de "' + @CONTROLE_PROBLEMA + '"' AS RECOMENDACAO,
        '-- Atualizar controle na nota: UPDATE TGFITE SET CONTROLE = ''' + (SELECT TOP 1 CONTROLE FROM @CONTROLES_SIMILARES WHERE STATUS = 'DISPONÍVEL' ORDER BY DISPONIVEL DESC) + ''' WHERE NUNOTA = [NUMERO_NOTA] AND SEQUENCIA = [SEQUENCIA]' AS COMANDO_SQL
    WHERE @TEM_SIMILAR_DISPONIVEL = 1 AND @TEM_CONTROLE_VALIDO = 0
    
    UNION ALL
    
    -- Opção 3: Criar novo controle
    SELECT 
        3 AS PRIORIDADE,
        'CRIAR NOVO CONTROLE' AS SITUACAO,
        'Criar um novo registro de estoque com o controle "' + @CONTROLE_PROBLEMA + '" transferindo estoque de outro controle disponível' AS RECOMENDACAO,
        '-- Inserir novo controle (cuidado com transferência): INSERT INTO TGFEST (...) SELECT ... FROM TGFEST WHERE CONTROLE = ''' + (SELECT TOP 1 CONTROLE FROM @CONTROLES_SIMILARES WHERE STATUS = 'DISPONÍVEL' ORDER BY DISPONIVEL DESC) + '''' AS COMANDO_SQL
    WHERE @TEM_SIMILAR_DISPONIVEL = 0
    
    UNION ALL
    
    -- Opção 4: Verificar outros locais
    SELECT 
        4 AS PRIORIDADE,
        'VERIFICAR OUTROS LOCAIS' AS SITUACAO,
        'O produto tem estoque disponível em outros locais. Considere usar outro local.' AS RECOMENDACAO,
        '-- Verificar estoque em outros locais: SELECT * FROM TGFEST WHERE CODPROD = ' + CAST(@CODPROD AS VARCHAR(10)) + ' AND CODEMP = ' + CAST(@CODEMP AS VARCHAR(5)) + ' ORDER BY (ESTOQUE - RESERVADO) DESC' AS COMANDO_SQL
    WHERE (SELECT COUNT(*) FROM TGFEST WHERE CODPROD = @CODPROD AND CODEMP = @CODEMP AND CODPARC = 0 AND (ESTOQUE - RESERVADO - ISNULL(WMSBLOQUEADO, 0)) > 0) = 1
) AS RECOMENDACOES
ORDER BY PRIORIDADE;
PRINT '';

-- 7. RESUMO FINAL
PRINT '=== 7. RESUMO FINAL DA INSPEÇÃO ===';
DECLARE @STATUS_FINAL VARCHAR(20);

IF @TEM_CONTROLE_VALIDO = 1
    SET @STATUS_FINAL = '✅ CONTROLE VÁLIDO';
ELSE IF @TEM_SIMILAR_DISPONIVEL = 1
    SET @STATUS_FINAL = '⚠️ CORRIGIR CONTROLE';
ELSE IF (SELECT COUNT(*) FROM @CONTROLES_SIMILARES) > 0
    SET @STATUS_FINAL = '❌ SEM DISPONÍVEL';
ELSE
    SET @STATUS_FINAL = '❌ SEM ESTOQUE';

PRINT '🎯 STATUS FINAL: ' + @STATUS_FINAL;
PRINT '📋 PRÓXIMOS PASSOS:';
PRINT CASE @STATUS_FINAL
    WHEN '✅ CONTROLE VÁLIDO' THEN '   1. Execute o script 04-validacao-final.sql';
    WHEN '⚠️ CORRIGIR CONTROLE' THEN '   1. Execute o script 03-correcao-controle.sql';
    WHEN '❌ SEM DISPONÍVEL' THEN '   1. Verifique se o produto está correto';
    WHEN '❌ SEM ESTOQUE' THEN '   1. Verifique necessidade de comprar mais estoque';
    ELSE '   1. Execute análise manual';
END;
PRINT '';

PRINT '=== FIM DA INSPEÇÃO COMPLETA ===';
PRINT '';