export const getOSManutencaoDetalhadaExecucoesQuery = `
SELECT
    e.NUOS,
    e.SEQUENCIA,
    e.CODUSU,
    LTRIM(RTRIM(u1.NOMEUSU)) AS USUARIO,
    e.CODUSUEXEC,
    LTRIM(RTRIM(u2.NOMEUSU)) AS EXECUTOR,
    e.DTINI,
    e.DTFIN,
    DATEDIFF(MINUTE, e.DTINI, e.DTFIN) AS TEMPO_MINUTOS,
    e.CODGRUPOPROD,
    CAST(e.OBS AS VARCHAR(MAX)) AS OBS
FROM SANKHYA.AD_TCFEXEC e
LEFT JOIN SANKHYA.TSIUSU u1 ON u1.CODUSU = e.CODUSU
LEFT JOIN SANKHYA.TSIUSU u2 ON u2.CODUSU = e.CODUSUEXEC
WHERE e.NUOS = @nuos
ORDER BY e.SEQUENCIA
`;
