export const getResumoManutencoesAtivasQuery = `
SELECT
    cab.NUOS,
    cab.CODVEICULO,
    v.PLACA,
    LTRIM(RTRIM(v.MARCAMODELO)) AS VEICULO,
    LTRIM(RTRIM(ISNULL(v.AD_TIPOEQPTO, v.CATEGORIA))) AS CATEGORIA,
    cab.STATUS,
    CASE cab.STATUS
        WHEN 'A' THEN 'Aberta'
        WHEN 'E' THEN 'Em Execução'
    END AS STATUS_DESCRICAO,
    cab.MANUTENCAO,
    CASE cab.MANUTENCAO
        WHEN 'C' THEN 'Corretiva'
        WHEN 'P' THEN 'Preventiva'
        WHEN 'O' THEN 'Outros'
    END AS MANUTENCAO_DESCRICAO,
    cab.DATAINI,
    cab.PREVISAO,
    DATEDIFF(DAY, cab.DATAINI, GETDATE()) AS DIAS_EM_MANUTENCAO,
    CASE
        WHEN cab.PREVISAO < GETDATE() THEN 'ATRASADA'
        WHEN cab.PREVISAO < DATEADD(DAY, 2, GETDATE()) THEN 'PROXIMA'
        ELSE 'NO_PRAZO'
    END AS SITUACAO_PRAZO,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOS s WHERE s.NUOS = cab.NUOS) AS QTD_SERVICOS,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOS s WHERE s.NUOS = cab.NUOS AND s.STATUS = 'F') AS SERVICOS_CONCLUIDOS,
    (SELECT TOP 1 LTRIM(RTRIM(p.DESCRPROD))
     FROM SANKHYA.TCFSERVOS s
     LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = s.CODPROD
     WHERE s.NUOS = cab.NUOS
     ORDER BY s.SEQUENCIA
    ) AS SERVICO_PRINCIPAL
FROM SANKHYA.TCFOSCAB cab
INNER JOIN SANKHYA.TGFVEI v ON v.CODVEICULO = cab.CODVEICULO
WHERE cab.STATUS IN ('A', 'E')
  AND cab.DATAFIN IS NULL
  AND v.AD_EXIBEDASH = 'S'
ORDER BY
    CASE
        WHEN cab.PREVISAO < GETDATE() THEN 0
        ELSE 1
    END,
    cab.DATAINI
`;
