export const getOSManutencaoAtivasByVeiculoQuery = `
SELECT
    cab.NUOS,
    cab.STATUS,
    CASE cab.STATUS
        WHEN 'A' THEN 'Aberta'
        WHEN 'E' THEN 'Em Execução'
    END AS STATUS_DESCRICAO,
    cab.TIPO,
    cab.MANUTENCAO,
    CASE cab.MANUTENCAO
        WHEN 'C' THEN 'Corretiva'
        WHEN 'P' THEN 'Preventiva'
        WHEN 'O' THEN 'Outros'
    END AS MANUTENCAO_DESCRICAO,
    cab.DATAINI,
    cab.PREVISAO,
    cab.KM,
    cab.HORIMETRO,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOS s WHERE s.NUOS = cab.NUOS) AS QTD_SERVICOS,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOS s WHERE s.NUOS = cab.NUOS AND s.STATUS = 'E') AS SERVICOS_EM_EXEC,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOS s WHERE s.NUOS = cab.NUOS AND s.STATUS = 'F') AS SERVICOS_FINALIZADOS,
    (SELECT COUNT(*) FROM SANKHYA.TCFSERVOSATO a WHERE a.NUOS = cab.NUOS) AS QTD_APONTAMENTOS,
    (SELECT COUNT(*) FROM SANKHYA.AD_TCFEXEC e WHERE e.NUOS = cab.NUOS) AS QTD_MECANICOS,
    -- Primeiro serviço pendente
    (SELECT TOP 1 LTRIM(RTRIM(p.DESCRPROD))
     FROM SANKHYA.TCFSERVOS s
     LEFT JOIN SANKHYA.TGFPRO p ON p.CODPROD = s.CODPROD
     WHERE s.NUOS = cab.NUOS AND (s.STATUS = 'E' OR s.STATUS IS NULL)
     ORDER BY s.SEQUENCIA
    ) AS SERVICO_PRINCIPAL
FROM SANKHYA.TCFOSCAB cab
WHERE cab.CODVEICULO = @codVeiculo
  AND cab.STATUS IN ('A', 'E')
  AND cab.DATAFIN IS NULL
ORDER BY cab.DATAINI DESC
`;
