-- ===================================================================
-- DIAGNÓSTICO DE ESTOQUE INSUFICIENTE - PRODUTO 15664
-- ===================================================================

-- 1. INFORMAÇÕES DO PRODUTO
SELECT '=== INFORMAÇÕES DO PRODUTO ===' AS INFO;
SELECT CODPROD, DESCRPROD, CODGRUPOPROD, USOPROD, ATIVO 
FROM TGFPRO 
WHERE CODPROD = 15664;

-- 2. INFORMAÇÕES DO GRUPO DE PRODUTOS
SELECT '=== INFORMAÇÕES DO GRUPO ===' AS INFO;
SELECT G.CODGRUPOPROD, G.VALEST, G.PEDIRLIB, G.AGRUPALOCVALEST
FROM TGFGRUPOPROD G
JOIN TGFPRO P ON G.CODGRUPOPROD = P.CODGRUPOPROD
WHERE P.CODPROD = 15664;

-- 3. ESTOQUE ATUAL POR CONTROLE
SELECT '=== ESTOQUE ATUAL POR CONTROLE ===' AS INFO;
SELECT CODEMP, CODLOCAL, CODPROD, CONTROLE, STATUSLOTE, 
       ESTOQUE, RESERVADO, WMSBLOQUEADO, ATIVO,
       (ESTOQUE - RESERVADO - ISNULL(WMSBLOQUEADO,0)) AS DISPONIVEL_SIMPLES
FROM TGFEST 
WHERE CODPROD = 15664 
  AND CODEMP = 1 
  AND CODLOCAL = 111003
  AND CODPARC = 0
ORDER BY CONTROLE;

-- 4. ESTOQUE ESPECÍFICO DO CONTROLE "9/16"" X 10"
SELECT '=== ESTOQUE DO CONTROLE ESPECÍFICO ===' AS INFO;
SELECT CODEMP, CODLOCAL, CODPROD, CONTROLE, STATUSLOTE, 
       ESTOQUE, RESERVADO, WMSBLOQUEADO, ATIVO,
       (ESTOQUE - RESERVADO - ISNULL(WMSBLOQUEADO,0)) AS DISPONIVEL_SIMPLES
FROM TGFEST 
WHERE CODPROD = 15664 
  AND CODEMP = 1 
  AND CODLOCAL = 111003
  AND CODPARC = 0
  AND (CONTROLE = '9/16" X 10' OR CONTROLE = '[TODOS]')
ORDER BY CONTROLE;

-- 5. PARÂMETROS DO SISTEMA
SELECT '=== PARÂMETROS DO SISTEMA ===' AS INFO;
SELECT CHAVE, LOGICO FROM TSIPAR 
WHERE CHAVE IN ('SOESTOQUE', 'WMSDESCONESTBLQ', 'SUBESTDOCAWMS', 'ATUALESTSERV')
ORDER BY CHAVE;

-- 6. INFORMAÇÕES DO LOCAL
SELECT '=== INFORMAÇÕES DO LOCAL ===' AS INFO;
SELECT CODLOCAL, DESCLOCAL, VALESTINDEP, AGRUPALOCVALEST
FROM TGFLOC 
WHERE CODLOCAL = 111003;

-- 7. VERIFICAÇÃO DE ESTOQUE EM DECOMPOSIÇÃO (WMS)
SELECT '=== ESTOQUE EM DECOMPOSIÇÃO WMS ===' AS INFO;
SELECT CODPROD, CONTROLE, CODEMP, CODLOCAL, 
       SANKHYA.F_WMS_GETESTOQUEDOCA(CODPROD, CONTROLE, CODEMP, CODLOCAL) AS ESTOQUE_DECOMPOSICAO
FROM TGFEST 
WHERE CODPROD = 15664 
  AND CODEMP = 1 
  AND CODLOCAL = 111003
  AND CODPARC = 0
  AND CONTROLE = '9/16" X 10';

-- 8. SIMULAÇÃO DO CÁLCULO DA PROCEDURE
SELECT '=== SIMULAÇÃO DO CÁLCULO ===' AS INFO;
DECLARE 
    @P_SOESTOQUE CHAR(1),
    @P_WMSDESCONESTBLQ CHAR(1),
    @P_SUBESTDOCAWMS CHAR(1),
    @VALEST_BLOQWMS_FAT CHAR(1),
    @ESTOQUE_CALCULADO FLOAT;

-- Busca parâmetros
SELECT @P_SOESTOQUE = ISNULL((SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'SOESTOQUE'), 'N');
SELECT @P_WMSDESCONESTBLQ = ISNULL((SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'WMSDESCONESTBLQ'), 'N');
SELECT @P_SUBESTDOCAWMS = ISNULL((SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'SUBESTDOCAWMS'), 'N');
SELECT @VALEST_BLOQWMS_FAT = ISNULL((SELECT VALEST_BLOQWMS_FAT FROM TSIULG WHERE SPID = @@SPID), 'N');

-- Calcula estoque disponível segundo a lógica da procedure
SELECT @ESTOQUE_CALCULADO = SUM(
    ESTOQUE - 
    (CASE WHEN @P_SOESTOQUE = 'N' THEN RESERVADO ELSE 0 END) -
    (CASE WHEN @P_WMSDESCONESTBLQ = 'S' AND @VALEST_BLOQWMS_FAT = 'S' THEN ISNULL(WMSBLOQUEADO,0) ELSE 0 END) -
    (CASE WHEN @P_SUBESTDOCAWMS = 'S' THEN SANKHYA.F_WMS_GETESTOQUEDOCA(CODPROD, CONTROLE, CODEMP, CODLOCAL) ELSE 0 END)
)
FROM TGFEST 
WHERE CODPROD = 15664 
  AND CODEMP = 1 
  AND CODLOCAL = 111003
  AND CODPARC = 0
  AND (CONTROLE = '9/16" X 10' OR CONTROLE = '[TODOS]');

SELECT 'Parâmetro SOESTOQUE: ' + @P_SOESTOQUE AS PARAMETRO;
SELECT 'Parâmetro WMSDESCONESTBLQ: ' + @P_WMSDESCONESTBLQ AS PARAMETRO;
SELECT 'Parâmetro SUBESTDOCAWMS: ' + @P_SUBESTDOCAWMS AS PARAMETRO;
SELECT 'Parâmetro VALEST_BLOQWMS_FAT: ' + @VALEST_BLOQWMS_FAT AS PARAMETRO;
SELECT 'Estoque Calculado Disponível: ' + CAST(ISNULL(@ESTOQUE_CALCULADO, 0) AS VARCHAR(20)) AS RESULTADO;

-- 9. VERIFICAÇÃO DE RESERVAS DO PRODUTO
SELECT '=== RESERVAS DO PRODUTO ===' AS INFO;
SELECT NUNOTA, CODPROD, CONTROLE, QTDNEG, QTDENTREGUE, RESERVA,
       (QTDNEG - QTDENTREGUE) AS PENDENTE
FROM TGFITE 
WHERE CODPROD = 15664 
  AND RESERVA > 0
ORDER BY NUNOTA DESC;

-- 10. VERIFICAÇÃO DE MOVIMENTOS RECENTES
SELECT '=== MOVIMENTOS RECENTES (ÚLTIMOS 30 DIAS) ===' AS INFO;
SELECT TOP 10 DTALTER, CODEMP, CODLOCAL, CODPROD, CONTROLE, 
       HISTORICO, ESTOQUE_ANT, ESTOQUE_ATU, QTDMOV, TIPMOV
FROM TGFHES 
WHERE CODPROD = 15664 
  AND DTALTER >= DATEADD(DAY, -30, GETDATE())
ORDER BY DTALTER DESC;

-- 11. EXECUÇÃO DA PROCEDURE ORIGINAL PARA TESTE
SELECT '=== TESTE DA PROCEDURE ORIGINAL ===' AS INFO;
DECLARE 
    @QUANTEST FLOAT,
    @VALEST_CHAR CHAR(1);

EXEC SANKHYA.STP_VALIDA_ESTOQUE40 
    @CODEMP = 1,
    @CODLOCALORIG = 111003,
    @CONTROLE = '9/16" X 10',
    @CODPROD = 15664,
    @STATUSLOTE = NULL,
    @TIPOESTOQUE = NULL,
    @QUANTEST = @QUANTEST OUTPUT,
    @VALEST = @VALEST_CHAR OUTPUT;

SELECT 'Resultado da Procedure - Quantidade: ' + CAST(ISNULL(@QUANTEST, 0) AS VARCHAR(20)) AS RESULTADO;
SELECT 'Resultado da Procedure - VALEST: ' + @VALEST_CHAR AS RESULTADO;

-- ===================================================================
-- FIM DO DIAGNÓSTICO
-- ===================================================================