
SELECT CAB.NUNOTA, PRO.DESCRPROD, ITE.CONTROLE, cab.OBSERVACAO,
  cab.AD_PRIORIDADE,
  -- DATEDIFF(DAY,LIB.DHLIB,CAB.AD_DTLIMITE) As qtdDiasLiberado
  -- , DATEDIFF(day, GETDATE(), AD_DTLIMITE)

  -- CAB.DTNEG,
  CONVERT(VARCHAR, CAB.DTNEG, 103) AS DTNEG2,
  lib.DHLIB,

  Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END AS diasLimite,

  DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB) as dhLimiteCalc



, CASE CAB.CODVEICULO
    WHEN 0 THEN 'Uso e Consumo'
    ELSE VEI.PLACA
    END AS APLICACAO
, USU.NOMEUSU, CONVERT(VARCHAR, AD_DTLIMITE, 103) AS DTLIMITE,





  -- Modify PRIORIDADE based on CONTROLE_DIAS and AD_PRIORIDADE
  CASE 
    WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 'PROGRAMADA URGENTE'
    ELSE CASE CAB.AD_PRIORIDADE
        WHEN 0 THEN 'EMERGÊNCIA'
        WHEN 1 THEN 'MUITO URGENTE'
        WHEN 2 THEN 'URGENTE'
        WHEN 3 THEN 'POUCO URGENTE'
        WHEN 4 THEN 'PROGRAMADA'
        END 
    END AS PRIORIDADE



-- Priority days based on AD_PRIORIDADE
, CASE WHEN CAB.AD_PRIORIDADE IS NOT NULL THEN CONCAT(CASE CAB.AD_PRIORIDADE
    WHEN 0 THEN 0
    WHEN 1 THEN 1
    WHEN 2 THEN 2
    WHEN 3 THEN 5
    WHEN 4 THEN 7
      END, ' Dia(s)', CASE CAB.AD_PRIORIDADE WHEN 4 THEN ' ou +' END) ELSE NULL END AS PRAZO

, DATEDIFF(day, GETDATE(), DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) AS CONTROLE_DIAS
,
  CASE
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) < 0 AND CAB.DTALTER > '2010-01-01' THEN '#000000'  -- preto: vencida
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FF0000' -- vermelho: ultimo dia
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#e67e22' -- laranja: 2 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#2874a6' -- azul: 5 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#b3b6b7' --  branco 7 dias ou mais

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#e000ff'
    
    END AS BKCOLOR,

  CASE 
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#ffffff'
    
    END AS FGCOLOR
FROM TGFCAB CAB
  JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
  JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
  JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
  JOIN TSIUSU USU ON USU.CODUSU = COALESCE(CAB.CODUSUINC, CAB.CODUSU)
  JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
WHERE ((QTDNEG - QTDENTREGUE) > 0 /*AND ITE.PENDENTE = 'S'*/)
  AND TIPMOV = 'Q'
  AND CAB.STATUSNOTA = 'L'
  AND CAB.CODTIPOPER IN (57)
  AND NUMCOTACAO IS NULL
  AND NUREM IS NULL
  AND ITE.CODPROD NOT IN (5568,6689,8076)
ORDER BY CONTROLE_DIAS, CAB.AD_PRIORIDADE,CAB.NUNOTA