-- SQL ORIGINAL: cotações em andamento aba 2
-- Extraído de geral.sql.compras.md

SELECT DISTINCT
-- CAB.AD_PRIORIDADE,
CASE
WHEN CAB.AD_PRIORIDADE is null THEN 'NÃO DEFINIDA'
WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 'PROGRAMADA URGENTE'
ELSE CASE CAB.AD_PRIORIDADE
WHEN 0 THEN 'EMERGÊNCIA'
WHEN 1 THEN 'MUITO URGENTE'
WHEN 2 THEN 'URGENTE'
WHEN 3 THEN 'POUCO URGENTE'
WHEN 4 THEN 'PROGRAMADA'
END
END AS PRIORIDADE,
CAB.NUNOTA,

    CAB.NUMCOTACAO,

    ITC.CODPROD,

    PRO.DESCRPROD,

    ITE.CONTROLE,

    USU.NOMEUSU,

    case
        when USUC.NOMEUSU = 'ROGERIO.JORDAO' THEN 'JORDÃO'
        ELSE CONCAT( LEFT(USUC.NOMEUSU, CHARINDEX('.',USUC.NOMEUSU) - 1), ' ', RIGHT(USUC.NOMEUSU, LEN(USUC.NOMEUSU) - CHARINDEX('.', USUC.NOMEUSU)))
    end AS COMPRADOR,

    USUL.NOMEUSU AS LIBERADOR
    ,CONVERT(VARCHAR,CAB.DTNEG,103) DTNEG
    ,DHLIB lib
    ,CASE
        WHEN DATEDIFF(MINUTE, DTNEG, DHLIB) < 60 THEN
            CAST(DATEDIFF(MINUTE, DTNEG, DHLIB) AS VARCHAR) + ' min'
        WHEN DATEDIFF(HOUR, DTNEG, DHLIB) < 24 THEN
            CAST(DATEDIFF(HOUR, DTNEG, DHLIB) AS VARCHAR) + ' horas'
        ELSE
            CAST(DATEDIFF(DAY, DTNEG, DHLIB) AS VARCHAR) + ' dias'
    END AS TimeDifference

    ,CONVERT(VARCHAR,AD_DTLIMITE,103) DTLIMITE --TESTE COLOCAR A DATA DA REQUIÇÃO

    ,DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) as DIASDIFF
    ,DATEDIFF(day, GETDATE(), AD_DTLIMITE) AS CONTROLE_DIAS
    -- ,DATEDIFF(day, GETDATE(), AD_DTLIMITE) AS DIAS_LIB DIAS DE LIBERACAO


    ,VEI.PLACA
    , CASE ITC.SITUACAO WHEN 'A' THEN 'APROVADA'
                        WHEN 'C' THEN 'RECUSADA'
                        WHEN 'E' THEN 'ENVIADA'
                        WHEN 'F' THEN 'FATURADA'
                        WHEN 'G' THEN 'NEGOCIAR'
                        WHEN 'N' THEN 'REPROVADA'
                        WHEN 'P' THEN 'PENDENTE'
                        WHEN 'R' THEN 'RESPONDIDA' END SITUACAOPROD,


    CASE
        WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 1 -- Programada Urgente
        WHEN CAB.AD_PRIORIDADE = 0 THEN 1 -- Emergência
        WHEN CAB.AD_PRIORIDADE = 1 THEN 2 -- Muito Urgente
        WHEN CAB.AD_PRIORIDADE = 2 THEN 3 -- Urgente
        WHEN CAB.AD_PRIORIDADE = 3 THEN 4 -- Pouco Urgente
        WHEN CAB.AD_PRIORIDADE = 4 THEN 5 -- Programada
        WHEN CAB.AD_PRIORIDADE is null THEN 99 -- sem prioridade

    END AS ORDEM_PRIORIDADE,
    CASE
    -- WHEN ITC.OBS like '%PAUSADA%' OR ITC.OBS like '%AGUARDANDO%'  THEN '#FFFF00'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) < 0 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#000000'  -- preto: vencida
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FF0000' -- vermelho: ultimo dia
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 2 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#E67E22' -- laranja: 2 dias
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 5 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 2 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#2874A6' -- azul: 5 dias
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 7 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 5 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#B3B6B7' --  branco 7 dias ou mais
        WHEN ITC.SITUACAO = 'A' AND COT.DTALTER > '2010-01-01' THEN '#28B463'   -- verde: aprovada

WHEN COT.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#e000ff'
END AS BKCOLOR,
CASE
-- WHEN ITC.OBS like '%PAUSADA%' OR ITC.OBS like '%AGUARDANDO%' THEN '#000000'
WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 2 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 5 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 2 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 7 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 5 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
WHEN ITC.SITUACAO = 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#ffffff'
END AS FGCOLOR
FROM TGFCAB CAB
LEFT JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
LEFT JOIN TSIUSU USUL ON USUL.CODUSU = LIB.CODUSULIB

    LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
    LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    LEFT JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
    LEFT JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC
    LEFT JOIN TGFCOT COT ON COT.NUMCOTACAO = CAB.NUMCOTACAO
    LEFT JOIN TSIUSU USUC ON USUC.CODUSU = COT.CODUSUREQ
    LEFT JOIN TGFITC ITC ON ITC.NUMCOTACAO = COT.NUMCOTACAO

where cot.NUMCOTACAO > 0
-- and cot.CODUSUREQ = 107
-- and ((ite.QTDNEG - ite.QTDENTREGUE) > 0)
-- and cab.NUNOTA = 80865
AND cot.SITUACAO NOT IN ('C', 'F')
AND cab.STATUSNOTA = 'L'
AND cab.CODTIPOPER IN (502, 504, 506, 507)
AND cab.TIPMOV = 'Q'
AND ITE.CODPROD NOT IN (5568, 6689, 8076)
AND ITE.CODPROD = ITC.CODPROD
AND ITE.CONTROLE = ITC.CONTROLE
AND ITC.CODPARC = 0
AND ITC.STATUSPRODCOT NOT IN ('C', 'F')
and (
SELECT count(*)
FROM TGFITC ITC2
WHERE ITC2.NUMCOTACAO = COT.NUMCOTACAO
AND ITC2.CODPROD = ITC.CODPROD
AND ITC2.CONTROLE = ITE.CONTROLE
AND ITC2.AD_NUNOTAPED IS NOT NULL
) <= 0
ORDER BY CONTROLE_DIAS, ORDEM_PRIORIDADE, CAB.NUMCOTACAO, ITC.CODPROD, PRO.DESCRPROD, ITE.CONTROLE