pendentes aba 3

/*SELECT DISTINCT CAB.NUNOTA
, CAB.DTNEG
, CAB.DTPREVENT
, PAR.NOMEPARC
, VEN.APELIDO
, USU.NOMEUSU
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TGFVEN VEN ON VEN.CODVEND      = CAB.CODVEND
LEFT JOIN TSIUSU USU ON USU.CODUSU       = CAB.CODUSUINC
WHERE ((QTDNEG - QTDENTREGUE > 0) AND ITE.PENDENTE = 'S')
    AND TIPMOV = 'O'
    AND CAB.STATUSNOTA = 'L'
    AND CAB.CODTIPOPER NOT IN (111,113,132,133,2800)*/

SELECT CASE WHEN CAB.NUMCOTACAO IS NOT NULL THEN COT.NUNOTAORIG ELSE CAB.AD_NUNOTAREQORIG END AS NURC,USUREQ.NOMEUSU AS REQUISITANTE, VEN.APELIDO, CAB.NUNOTA, CAB.NUMCOTACAO,  PRO.DESCRPROD, ITE.CONTROLE
, CASE CAB.CODVEICULO 
    WHEN 0 THEN 'Uso e Consumo' 
    ELSE VEI.PLACA 
    END AS APLICACAO
, USU.NOMEUSU AS COMPRADOR, CONVERT(VARCHAR,CAB.DTNEG,103) DTNEG , CAB.DTPREVENT
, CONCAT(PAR.CODPARC, ' - ', PAR.NOMEPARC) AS FORNECEDOR
, PAR.CGC_CPF
, CASE CAB.AD_PRIORIDADE
    WHEN 0 THEN 'EMERGÊNCIA'
    WHEN 1 THEN 'MUITO URGENTE'
    WHEN 2 THEN 'URGENTE'
    WHEN 3 THEN 'POUCO URGENTE'
    WHEN 4 THEN 'PROGRAMADA'
        END PRIORIDADE
, CASE CAB.AD_PRIORIDADE
		WHEN 0 THEN '#FF9393'
		WHEN 1 THEN '#FFCCCC'
		WHEN 2 THEN '#EDE73D'
		WHEN 3 THEN '#35C7F5'
		WHEN 4 THEN '#B8B8B8'
		 END AS BKCOLOR
, CASE WHEN CAB.AD_PRIORIDADE IS NOT NULL THEN CONCAT(CASE CAB.AD_PRIORIDADE
    WHEN 0 THEN 0
    WHEN 1 THEN 1
    WHEN 2 THEN 2
    WHEN 3 THEN 5
    WHEN 4 THEN '+7'
        END,' Dia(s)') ELSE NULL END PRAZO
, DATEDIFF(day, GETDATE(), CAB.DTPREVENT) AS 'CONTROLE_DIAS'
FROM TGFCAB CAB
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC

LEFT JOIN TGFCOT COT ON COT.NUMCOTACAO = CAB.NUMCOTACAO
LEFT JOIN TGFCAB REQ ON REQ.NUNOTA = (CASE WHEN CAB.NUMCOTACAO IS NOT NULL THEN COT.NUNOTAORIG ELSE CAB.AD_NUNOTAREQORIG END)
LEFT JOIN TSIUSU USUREQ ON USUREQ.CODUSU = REQ.CODUSUINC

WHERE ((QTDNEG - QTDENTREGUE > 0) AND ITE.PENDENTE = 'S')
    AND CAB.CODUSUINC NOT IN (172,22)
    AND CAB.TIPMOV = 'O'
    AND CAB.STATUSNOTA = 'L'
    AND CAB.CODTIPOPER  NOT IN (3,111,113,132,133,2800)
    AND ITE.CODPROD NOT IN (2519,5044,99999)
ORDER BY 1 DESC


cotações em andamento aba 2

SELECT DISTINCT
-- CAB.AD_PRIORIDADE,
    CASE
        WHEN CAB.AD_PRIORIDADE is null THEN 'NÃO DEFINIDA'
        WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 'PROGRAMADA URGENTE'
        ELSE CASE CAB.AD_PRIORIDADE
            WHEN 0 THEN 'EMERGÊNCIA'
            WHEN 1 THEN 'MUITO URGENTE'
            WHEN 2 THEN 'URGENTE'
            WHEN 3 THEN 'POUCO URGENTE'
            WHEN 4 THEN 'PROGRAMADA'
        END
    END AS PRIORIDADE,
    CAB.NUNOTA, 
    
    CAB.NUMCOTACAO, 
    
    ITC.CODPROD, 
    
    PRO.DESCRPROD, 
    
    ITE.CONTROLE, 
    
    USU.NOMEUSU, 
    
    case 
        when USUC.NOMEUSU = 'ROGERIO.JORDAO' THEN 'JORDÃO'
        ELSE CONCAT( LEFT(USUC.NOMEUSU, CHARINDEX('.',USUC.NOMEUSU) - 1), ' ', RIGHT(USUC.NOMEUSU, LEN(USUC.NOMEUSU) - CHARINDEX('.', USUC.NOMEUSU)))
    end AS COMPRADOR,

    USUL.NOMEUSU AS LIBERADOR
    ,CONVERT(VARCHAR,CAB.DTNEG,103) DTNEG
    ,DHLIB lib
    ,CASE
        WHEN DATEDIFF(MINUTE, DTNEG, DHLIB) < 60 THEN 
            CAST(DATEDIFF(MINUTE, DTNEG, DHLIB) AS VARCHAR) + ' min'
        WHEN DATEDIFF(HOUR, DTNEG, DHLIB) < 24 THEN 
            CAST(DATEDIFF(HOUR, DTNEG, DHLIB) AS VARCHAR) + ' horas'
        ELSE 
            CAST(DATEDIFF(DAY, DTNEG, DHLIB) AS VARCHAR) + ' dias'
    END AS TimeDifference
    
    ,CONVERT(VARCHAR,AD_DTLIMITE,103) DTLIMITE --TESTE COLOCAR A DATA DA REQUIÇÃO

    ,DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) as DIASDIFF
    ,DATEDIFF(day, GETDATE(), AD_DTLIMITE) AS CONTROLE_DIAS
    -- ,DATEDIFF(day, GETDATE(), AD_DTLIMITE) AS DIAS_LIB DIAS DE LIBERACAO


    ,VEI.PLACA
    , CASE ITC.SITUACAO WHEN 'A' THEN 'APROVADA'
                        WHEN 'C' THEN 'RECUSADA'
                        WHEN 'E' THEN 'ENVIADA'
                        WHEN 'F' THEN 'FATURADA'
                        WHEN 'G' THEN 'NEGOCIAR'
                        WHEN 'N' THEN 'REPROVADA'
                        WHEN 'P' THEN 'PENDENTE'
                        WHEN 'R' THEN 'RESPONDIDA' END SITUACAOPROD,


    CASE
        WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 1 -- Programada Urgente
        WHEN CAB.AD_PRIORIDADE = 0 THEN 1 -- Emergência
        WHEN CAB.AD_PRIORIDADE = 1 THEN 2 -- Muito Urgente
        WHEN CAB.AD_PRIORIDADE = 2 THEN 3 -- Urgente
        WHEN CAB.AD_PRIORIDADE = 3 THEN 4 -- Pouco Urgente
        WHEN CAB.AD_PRIORIDADE = 4 THEN 5 -- Programada
        WHEN CAB.AD_PRIORIDADE is null THEN 99 -- sem prioridade

    END AS ORDEM_PRIORIDADE,
    CASE
    -- WHEN ITC.OBS like '%PAUSADA%' OR ITC.OBS like '%AGUARDANDO%'  THEN '#FFFF00'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) < 0 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#000000'  -- preto: vencida
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FF0000' -- vermelho: ultimo dia
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 2 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#E67E22' -- laranja: 2 dias
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 5 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 2 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#2874A6' -- azul: 5 dias
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 7 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 5 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#B3B6B7' --  branco 7 dias ou mais
        WHEN ITC.SITUACAO = 'A' AND COT.DTALTER > '2010-01-01' THEN '#28B463'   -- verde: aprovada

WHEN COT.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#e000ff'
    END AS BKCOLOR,
    CASE
        -- WHEN ITC.OBS like '%PAUSADA%' OR ITC.OBS like '%AGUARDANDO%'  THEN '#000000'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 2 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 1 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 5 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 2 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) <= 7 AND DATEDIFF(DAY,GETDATE(),AD_DTLIMITE) > 5 AND ITC.SITUACAO <> 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN ITC.SITUACAO = 'A' AND COT.DTALTER > '2010-01-01' THEN '#FFFFFF'

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#ffffff'
    END AS FGCOLOR
FROM TGFCAB CAB
    LEFT JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
    LEFT JOIN TSIUSU USUL ON USUL.CODUSU = LIB.CODUSULIB

    LEFT JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
    LEFT JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
    LEFT JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
    LEFT JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC
    LEFT JOIN TGFCOT COT ON COT.NUMCOTACAO = CAB.NUMCOTACAO
    LEFT JOIN TSIUSU USUC ON USUC.CODUSU = COT.CODUSUREQ
    LEFT JOIN TGFITC ITC ON ITC.NUMCOTACAO = COT.NUMCOTACAO
where  cot.NUMCOTACAO > 0
    -- and cot.CODUSUREQ = 107
    -- and ((ite.QTDNEG - ite.QTDENTREGUE) > 0)
    -- and cab.NUNOTA = 80865
    AND cot.SITUACAO NOT IN ('C', 'F')
    AND cab.STATUSNOTA = 'L'
    AND cab.CODTIPOPER IN (502, 504, 506, 507)
    AND cab.TIPMOV = 'Q'
    AND ITE.CODPROD NOT IN (5568, 6689, 8076)
    AND ITE.CODPROD = ITC.CODPROD
    AND ITE.CONTROLE = ITC.CONTROLE
    AND ITC.CODPARC = 0
    AND ITC.STATUSPRODCOT NOT IN ('C', 'F')
    and (
    SELECT count(*)
    FROM TGFITC ITC2
    WHERE ITC2.NUMCOTACAO = COT.NUMCOTACAO
        AND ITC2.CODPROD = ITC.CODPROD
        AND ITC2.CONTROLE = ITE.CONTROLE
        AND ITC2.AD_NUNOTAPED IS NOT NULL
) <= 0
ORDER BY CONTROLE_DIAS, ORDEM_PRIORIDADE, CAB.NUMCOTACAO, ITC.CODPROD, PRO.DESCRPROD, ITE.CONTROLE



requisições em aberto geral aba 1

SELECT 
(SELECT [SANKHYA].[STP_GET_CODUSULOGADO]() FROM DUAL) as logged_user_1, 
(SELECT CODUSU FROM TSIULG WHERE SPID = @@SPID) as logged_user_2, 
CAB.NUNOTA, PRO.DESCRPROD, ITE.CONTROLE, cab.OBSERVACAO,
cab.AD_PRIORIDADE,
-- DATEDIFF(DAY,LIB.DHLIB,CAB.AD_DTLIMITE) As qtdDiasLiberado,
-- DATEDIFF(day, GETDATE(), AD_DTLIMITE),
-- CAB.DTNEG,
CONVERT(VARCHAR, CAB.DTNEG, 103) AS DTNEG2,
lib.DHLIB,

Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END AS diasLimite,

DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB) as dhLimiteCalc,

CASE CAB.CODVEICULO
    WHEN 0 THEN 'Uso e Consumo'
    ELSE VEI.PLACA
    END AS APLICACAO,
USU.NOMEUSU,
CONVERT(VARCHAR, AD_DTLIMITE, 103) AS DTLIMITE,

-- Modify PRIORIDADE based on CONTROLE_DIAS and AD_PRIORIDADE
 CASE 
    WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 'Programada Urgente'
    ELSE CASE CAB.AD_PRIORIDADE
        WHEN 0 THEN '0.Emergência - 0 a 1 dia para chegar'
        WHEN 1 THEN '1.Muito urgente - 0 a 3 dias para chegar'
        WHEN 2 THEN '2.Normal - 0 a 5 dias para chegar'
        WHEN 3 THEN '3.Programada prazo curto - 0 a 10 dias para chegar'
        WHEN 4 THEN '4.Programada prazo longo - 0 a 30 dias para chegar'
        END 
    END AS PRIORIDADE,

-- Priority days based on AD_PRIORIDADE
CASE WHEN CAB.AD_PRIORIDADE IS NOT NULL THEN CONCAT(CASE CAB.AD_PRIORIDADE
    WHEN 0 THEN '0 a 1'
    WHEN 1 THEN '0 a 3'
    WHEN 2 THEN '0 a 5'
    WHEN 3 THEN '0 a 10'
    WHEN 4 THEN '0 a 30'
      END, ' Dia(s)', CASE CAB.AD_PRIORIDADE WHEN 4 THEN ' ou +' END) ELSE NULL END AS PRAZO,

DATEDIFF(day, GETDATE(), DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) AS CONTROLE_DIAS,
   
CASE WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) < 0  AND CAB.DTALTER > '2010-01-01' THEN '#000000'  -- preto: vencida
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FF0000' -- vermelho: ultimo dia
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#e67e22' -- laranja: 2 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#2874a6' -- azul: 5 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#b3b6b7' --  branco 7 dias ou mais

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#e000ff'
    
    END AS BKCOLOR,

    CASE 
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#ffffff'    END AS FGCOLOR
FROM TGFCAB CAB
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
JOIN TSIUSU USU ON USU.CODUSU = COALESCE(CAB.CODUSUINC, CAB.CODUSU)
JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
WHERE ((QTDNEG - QTDENTREGUE) > 0)
    AND TIPMOV = 'Q'
    AND CAB.STATUSNOTA = 'L'
    AND CAB.CODTIPOPER IN (502,504,506,507)
    AND NUMCOTACAO IS NULL
    AND NUREM IS NULL
    AND ITE.CODPROD NOT IN (5568,6689,8076)
    AND (
    (SELECT CODUSU FROM TSIULG WHERE SPID = @@SPID) NOT IN (309) -- CLAUSAULA PARA NAO APARECER COMPRAS PENDENTES PRO COMPRADOR DO USUARIO 308 - DANUBIA
    OR CAB.CODUSU <> 308
    OR (SELECT CODUSU FROM TSIULG WHERE SPID = @@SPID) IS NULL
)
ORDER BY CONTROLE_DIAS asc, CAB.AD_PRIORIDADE,  CAB.NUNOTA

requisicoes pendentes do manutenção 

SELECT CAB.NUNOTA, PRO.DESCRPROD, ITE.CONTROLE, cab.OBSERVACAO,
cab.AD_PRIORIDADE,
-- DATEDIFF(DAY,LIB.DHLIB,CAB.AD_DTLIMITE) As qtdDiasLiberado
-- , DATEDIFF(day, GETDATE(), AD_DTLIMITE)

-- CAB.DTNEG,
CONVERT(VARCHAR, CAB.DTNEG, 103) AS DTNEG2,
lib.DHLIB,

Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END AS diasLimite,

DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB) as dhLimiteCalc



, CASE CAB.CODVEICULO
    WHEN 0 THEN 'Uso e Consumo'
    ELSE VEI.PLACA
    END AS APLICACAO
, USU.NOMEUSU,  CONVERT(VARCHAR, AD_DTLIMITE, 103) AS DTLIMITE,





-- Modify PRIORIDADE based on CONTROLE_DIAS and AD_PRIORIDADE
 CASE 
    WHEN CAB.AD_PRIORIDADE = 4 AND DATEDIFF(day, GETDATE(), AD_DTLIMITE) <= 1 THEN 'PROGRAMADA URGENTE'
    ELSE CASE CAB.AD_PRIORIDADE
        WHEN 0 THEN 'EMERGÊNCIA'
        WHEN 1 THEN 'MUITO URGENTE'
        WHEN 2 THEN 'URGENTE'
        WHEN 3 THEN 'POUCO URGENTE'
        WHEN 4 THEN 'PROGRAMADA'
        END 
    END AS PRIORIDADE



-- Priority days based on AD_PRIORIDADE
, CASE WHEN CAB.AD_PRIORIDADE IS NOT NULL THEN CONCAT(CASE CAB.AD_PRIORIDADE
    WHEN 0 THEN 0
    WHEN 1 THEN 1
    WHEN 2 THEN 2
    WHEN 3 THEN 5
    WHEN 4 THEN 7
      END, ' Dia(s)', CASE CAB.AD_PRIORIDADE WHEN 4 THEN ' ou +' END) ELSE NULL END AS PRAZO

, DATEDIFF(day, GETDATE(), DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) AS CONTROLE_DIAS
,
    CASE
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) < 0  AND CAB.DTALTER > '2010-01-01' THEN '#000000'  -- preto: vencida
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FF0000' -- vermelho: ultimo dia
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#e67e22' -- laranja: 2 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#2874a6' -- azul: 5 dias
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#b3b6b7' --  branco 7 dias ou mais

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#e000ff'
    
    END AS BKCOLOR,

    CASE 
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 2 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 1 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 5 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 2 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'
        WHEN DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) <= 7 AND DATEDIFF(DAY,GETDATE(),DATEADD(DAY,Case 
    when CAB.AD_PRIORIDADE = 0 THEN 1
    when CAB.AD_PRIORIDADE = 1 THEN 3
    when CAB.AD_PRIORIDADE = 2 THEN 5
    when CAB.AD_PRIORIDADE = 3 THEN 10
    when CAB.AD_PRIORIDADE = 4 THEN 30
    ELSE 0
END ,LIB.DHLIB)) > 5 AND CAB.DTALTER > '2010-01-01' THEN '#FFFFFF'

WHEN CAB.OBSERVACAO like '%FILIPE%' OR CAB.OBSERVACAO like '%WILSON%' OR CAB.OBSERVACAO like '%CANDIDA%' OR CAB.OBSERVACAO like '%NATALIA%' THEN '#ffffff'
    
    END AS FGCOLOR
FROM TGFCAB CAB
JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
JOIN TGFVEI VEI ON VEI.CODVEICULO = CAB.CODVEICULO
JOIN TSIUSU USU ON USU.CODUSU = COALESCE(CAB.CODUSUINC, CAB.CODUSU)
JOIN TSILIB LIB ON LIB.NUCHAVE = CAB.NUNOTA
WHERE ((QTDNEG - QTDENTREGUE) > 0 /*AND ITE.PENDENTE = 'S'*/)
    AND TIPMOV = 'Q'
    AND CAB.STATUSNOTA = 'L'
    AND CAB.CODTIPOPER IN (57)
    AND NUMCOTACAO IS NULL
    AND NUREM IS NULL
    AND ITE.CODPROD NOT IN (5568,6689,8076) 
ORDER BY CONTROLE_DIAS, CAB.AD_PRIORIDADE,CAB.NUNOTA