-- SQL ORIGINAL: pendentes aba 3
-- Extraído de geral.sql.compras.md

SELECT DISTINCT CAB.NUNOTA
, CAB.DTNEG
, CAB.DTPREVENT
, PAR.NOMEPARC
, VEN.APELIDO
, USU.NOMEUSU
FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC
LEFT JOIN TGFVEN VEN ON VEN.CODVEND = CAB.CODVEND
LEFT JOIN TSIUSU USU ON USU.CODUSU = CAB.CODUSUINC
WHERE ((QTDNEG - QTDENTREGUE > 0) AND ITE.PENDENTE = 'S')
AND TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND CAB.CODTIPOPER NOT IN (111,113,132,133,2800)