-- Variant: Valor em Estoque por Período por local (CODEMP, CODLOCAL)
-- Agrupa o valor remanescente por produto e local

DECLARE @dtInicio DATE = '2025-01-01';
DECLARE @dtFim    DATE = '2025-12-31';

WITH
  purchases_period
  AS
  (
    SELECT
      i.CODPROD,
      c.CODEMP,
      i.CODLOCAL,
      SUM(ISNULL(i.QTDNEG,0)) AS QTD_COMPRADA,
      SUM(ISNULL(i.VLRUNIT,0)*ISNULL(i.QTDNEG,0)) AS VALOR_TOTAL_COMPRAS,
      CASE WHEN SUM(ISNULL(i.QTDNEG,0))>0 THEN SUM(ISNULL(i.VLRUNIT,0)*ISNULL(i.QTDNEG,0))/SUM(ISNULL(i.QTDNEG,0)) ELSE NULL END AS PRECO_PONDERADO
    FROM [SANKHYA].[TGFCAB] c
      JOIN [SANKHYA].[TGFITE] i ON i.NUNOTA = c.NUNOTA
    WHERE c.TIPMOV = 'O' AND c.STATUSNOTA = 'L' AND c.DTMOV BETWEEN @dtInicio AND @dtFim
    GROUP BY i.CODPROD, c.CODEMP, i.CODLOCAL
  ),
  stock_local
  AS
  (
    SELECT CODEMP, CODLOCAL, CODPROD, SUM(ISNULL(ESTOQUE,0)) AS ESTOQUE_ATUAL
    FROM [SANKHYA].[TGFEST]
    GROUP BY CODEMP, CODLOCAL, CODPROD
  ),
  last_purchase_price
  AS
  (
    SELECT t.CODPROD, t.VLRUNIT as last_vlrunit
    FROM (
    SELECT I.CODPROD, I.VLRUNIT,
        ROW_NUMBER() OVER (PARTITION BY I.CODPROD ORDER BY C.DTNEG DESC, I.NUNOTA DESC) as rn
      FROM [SANKHYA].[TGFITE] I
        JOIN [SANKHYA].[TGFCAB] C ON C.NUNOTA = I.NUNOTA AND C.TIPMOV = 'C' AND C.STATUSNOTA = 'L'
  ) t
    WHERE t.rn = 1
  )

SELECT
  pp.CODEMP,
  pp.CODLOCAL,
  pp.CODPROD,
  pr.DESCRPROD,
  ISNULL(sl.ESTOQUE_ATUAL,0) AS ESTOQUE_ATUAL,
  pp.QTD_COMPRADA,
  COALESCE(pp.PRECO_PONDERADO, lp.last_vlrunit, pr.VLRUNIT, 0) AS PRECO_USADO,
  CASE WHEN ISNULL(sl.ESTOQUE_ATUAL,0) < ISNULL(pp.QTD_COMPRADA,0) THEN ISNULL(sl.ESTOQUE_ATUAL,0) ELSE ISNULL(pp.QTD_COMPRADA,0) END AS QTD_APLICAVEL,
  (CASE WHEN ISNULL(sl.ESTOQUE_ATUAL,0) < ISNULL(pp.QTD_COMPRADA,0) THEN ISNULL(sl.ESTOQUE_ATUAL,0) ELSE ISNULL(pp.QTD_COMPRADA,0) END) * COALESCE(pp.PRECO_PONDERADO, lp.last_vlrunit, pr.VLRUNIT, 0) AS VALOR_REMANESCENTE
FROM purchases_period pp
  LEFT JOIN stock_local sl ON sl.CODPROD = pp.CODPROD AND sl.CODEMP = pp.CODEMP AND sl.CODLOCAL = pp.CODLOCAL
  LEFT JOIN last_purchase_price lp ON lp.CODPROD = pp.CODPROD
  LEFT JOIN [SANKHYA].[TGFPRO] pr ON pr.CODPROD = pp.CODPROD
ORDER BY VALOR_REMANESCENTE DESC;